POST http://localhost:3000/notifications?paramA=valueA&def=zerq
Foo: bar

BLABLABLA

###
#GET http://localhost:3000/notification-results?from_id=12&from_date=2020-05-22T19:28:00%2B02:00
GET http://localhost:3000/notification-results?from_id=2&from_date=2020-05-22T19:28:00Z

###
POST http://localhost:3000/echo/reversed


NAJAL
###
